source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'


def all_pods
######################## Local ============================
  pod 'SwiftyJSON', :path => '../SwiftyJSON'
  pod 'HandyJSON', :path => '../HandyJSON'
  pod 'Codextended', :path => '../Codextended'
  pod 'ObjectMapper', :path => '../ObjectMapper/'
end

target 'RacTest_Swift' do
  all_pods
end
