source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'


def all_pods
  pod 'Masonry'
  pod 'IQKeyboardManager'
#  pod 'ReactiveObjC'
#  pod 'AFNetworking'
#  pod 'WCDB'
#  pod 'JSONModel'
#  pod 'MJRfresh'
#  pod 'MJExtension'

######################## Local ============================
  pod 'ReactiveObjC', :path => '../ReactiveObjC/'
  pod 'AFNetworking', :path => '../AFNetworking/'
  pod 'WCDB', :path => '../wcdb-1.0.8.2/'
  pod 'MJRefresh', :path => '../MJRefresh-3.3.1/'
  pod 'JSONModel', :path => '../JSONModel/'
  pod 'YYModel', :path => '../YYModel/'
  pod 'YYCache', :path => '../YYCache/'
  pod 'SDWebImage', :path => '../SDWebImage/'
  pod 'MJExtension', :path => '../MJExtension/'
  pod 'KVOController', :path => '../KVOController/'
  pod 'CTMediator', :path => '../CTMediator/'
  pod 'VKURLAction', :path => '../VKURLAction/'
  
#  pod 'SDWebImageWebPCoder', :path => '../SDWebImageWebPCoder/'
  
######################## CommonLib ========================
  pod 'LTCoreKit', :path => '../../LTCoreKit/'
  pod 'LTUIKit', :path => '../../LTUIKit/'
  pod 'LTNetMonitor', :path => '../../LTNetMonitor'
  pod 'LTMacro', :path => '../../LTMacro'
  pod 'LTRouter', :path => '../../LTRouter'
  pod 'LTNetRequestManager', :path => '../../LTNetRequestManager'
end

target 'RacTest_OC' do
  all_pods
end
