source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'


def all_pods
  pod 'Masonry'
#  pod 'ReactiveObjC'
#  pod 'WCDB'
  pod 'ReactiveObjC', :path => '../ReactiveObjC/'
  pod 'AFNetworking', :path => '../AFNetworking/'
  pod 'AFNetworking', :path => '../WCDB/'
  pod 'IQKeyBoardManager'
  
end

target 'RacTest_OC' do
  all_pods
end
